### ISSUE TITLE
Implement A133613

### ISSUE THREAD

**Issue by cheznewa** [JulienPalard/oeis#259]
Last Digits Of Graham's Number

**Comment by JulienPalard** [comment]
PR welcome :)

**Comment by cheznewa** [comment]
I Need The "stop" Variable I Can't Get Here ...

**Comment by JulienPalard** [comment]
What's your current implementation? I'll take a look at what we can do.

**Comment by yalla** [comment]
So, I do have A133613 ready, along with A183613 which is the enabling function.
However, do to the recursive nature of A183613, it's neither performant nor can anyone guarantee that it will terminate at all.
I can say that A133613[0:7] works happily, but once you hit n=8, things become ugly.
So I can push a version, but I'm not exactly sure if that's the right approach doing things programmatically. Maybe for this sequence it would be better to return a static list which was pulled directly from OEIS, and someone else already did the heavy lifting.
I didn't even bother to commit it to my own repo as this is kinda stupid, so I'm just pasting the code here.

```python
@oeis.from_function(offset=1)
def A183613(n: int) -> int:
    """Give a(n) = 3^^(n+1) modulo 10^n.
    
    Warning: Although this works, it becomes ugly at n > 7.
    For n>1, a(n) = 3^a(n-1) mod 10^n"""

    def intA183613(n):
        if n == 1:
            return 7
        return 3**intA183613(n-1) % (10 ** n)

    if n == 1:
        return 7
    return intA183613(n)
```

And now the sequence in question:

```python
@oeis.from_function(offset=0)
def A133613(n: int) -> int:
    """Decimal digits such that for all k>=1, the number A(k) := Sum_{n = 0..k-1 } a(n)*10^n,
    
    satisfies the congruence 3^A(k) == A(k) (mod 10^k).
    a(n) = floor( A183613(n+1) / 10^n ). 
    """
    from math import floor
    return floor(A183613[n+1] / 10**n)
```

You probably shouldn't run this on a machine with restricted resources. Or maybe someone has a better algorithm ready.

**Comment by JulienPalard** [comment]
I can do:

```
def A183613(i):
    x = 3
    for t in range(1, i+1):
        x = pow(3, x, pow(10, t))
    return x
```

**Comment by cheznewa** [comment]
So, When You Implement It?
