### ISSUE TITLE
Implement A007953

### ISSUE THREAD

**Issue by valugit** [JulienPalard/oeis#56]
I'm implementing this sequence.

**Comment by valugit** [comment]
Switching to A007953, because it seems python doesn't like big float...

**Comment by JulienPalard** [comment]
You may try using the decimal module for big floats, like:
```python
from decimal import localcontext, Decimal

with localcontext() as ctx:
    ctx.prec = 99
    print((1 + Decimal(5).sqrt()) / 2)
```

Attention `.prec` à une limite haute aussi ...

**Comment by valugit** [comment]
I will try this. I looked at decimal but didn't figure out what to use to make it work. I will open another issue for the sequence A001622.
